spring:
  profiles.active: default
---
spring:
  profiles: default

  jpa:
    show-sql: false

    hibernate:
      ddl-auto: validate
      database-platformString: org.hibernate.dialect.MySQLDialect

    properties:
      hibernate.dialect: org.hibernate.dialect.MySQL5Dialect

  # Keep the connection alive if idle for a long time (needed in production)
  datasource:
    url: jdbc:mysql://localhost/wine_draw?useSSL=false
    username: winedrawuser
    password: R5PcSelIp0jCWSXJ6xPd
    testWhileIdle: true
    validationQuery: SELECT 1

security:
  filter-order: 5

# We want to manually run migrations
flyway:
  enabled: false

server:
  tomcat:
    access-log-enabled: true
    access-log-pattern: "%a asdasd"

identifier: development